# -*- coding: utf-8 -*-

require 'yaml'

def start_pgrp(*cmds)
  pgid = fork{
    Process.setpgid($$, $$)
    sh *cmds
  }
  Process.setpgid(pgid, pgid)

  pgid
end

def run_server(*options)
  pgid = start_pgrp('rims', 'server', *options)
  begin
    sleep 1
    yield
  ensure
    Process.kill('TERM', -pgid)
    Process.wait
  end
end

def run_server_conf(path, conf, *options)
  mkdir_p(path)

  path_conf = File.join(path, 'config.yml')
  IO.write(path_conf, conf.to_yaml)

  run_server('-f', path_conf, *options) do
    yield
  end
end

task :server do
  conf = {
    'user_list' => [
      { 'user' => 'foo', 'pass' => 'foo' },
      { 'user' => '#postman', 'pass' => '#postman' }
    ]
  }
  run_server_conf('imap_append', conf, *%w[ -l debug --ip-addr=localhost --ip-port=14300 ]) do
    sleep(10)
  end
end

# Local Variables:
# mode: Ruby
# indent-tabs-mode: nil
# End:
